version: "3.1"
services:

  moviepy:
    build:
      context: .
    image: lopesivan/moviepy:1.0
    container_name: moviepy
    command: python app/script.py
    network_mode: "none"
    volumes:
       - ${PWD}:/code
